from enum import Enum, auto

class TorrentState(Enum):
    WAITING_FOR_SELECTION = "WAITING_FOR_SELECTION"
    WAITING_FOR_REALDEBRID = "WAITING_FOR_REALDEBRID"
    DOWNLOADING_ON_REALDEBRID = "DOWNLOADING_ON_REALDEBRID"
    AVAILABLE_FROM_REALDEBRID = "AVAILABLE_FROM_REALDEBRID"
    WAITING_IN_QUEUE = "WAITING_IN_QUEUE"
    DOWNLOADING_FROM_REALDEBRID = "DOWNLOADING_FROM_REALDEBRID"
    TRANSFERRING_TO_MEDIA_SERVER = "TRANSFERRING_TO_MEDIA_SERVER"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
    WAITING_FOR_METADATA = "WAITING_FOR_METADATA"

    def __str__(self):
        return self.name